title: Lemuel Roberto
author: Lemuel Roberto
description: > # this means to ignore newlines until "baseurl:"
  Some notes and learnings for my future self.
baseurl: ""
twitter_username: lemuelroberto
github_username:  lemuelroberto

minima:
  date_format: "%b %-d, %Y"

exclude:
  - README.md
  - LICENSE.txt
  - Makefile
  - .gitignore
