title: Lemuel Roberto
author: Lemuel Roberto
description: > # this means to ignore newlines until "baseurl:"
  My learnings on tech and nerd stuff.
baseurl: ""
twitter_username: lemuelroberto
github_username:  lemuelroberto

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

exclude:
  - README.md
  - LICENSE.txt
  - Makefile
  - .gitignore
